version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: folcklore-app
    restart: unless-stopped
    ports:
      - "3003:80"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_KEY=${APP_KEY}
      - APP_URL=${APP_URL:-http://localhost}
      # Use external database - configure these in Coolify
      - DB_CONNECTION=mysql
      - DB_HOST=${DB_HOST:-localhost}
      - DB_PORT=${DB_PORT:-3306}
      - DB_DATABASE=${DB_DATABASE:-folcklore}
      - DB_USERNAME=${DB_USERNAME:-root}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - storage:/var/www/storage
      - logs:/var/www/storage/logs

volumes:
  storage:
    driver: local
  logs:
    driver: local